### ISSUE TITLE
移动端测试api能够正常对话，但qq上发送消息报错message为空

### ISSUE THREAD

**Issue by danel-phang** [Pasumao/nonebot-plugin-wx4#1]
![捕获](https://github.com/Pasumao/nonebot-plugin-wx4/assets/145145476/f8fecd7a-8751-415e-85a0-9e3ae18d12a6)

**Comment by danel-phang** [comment]
用的是llob

**Comment by Pasumao** [comment]
我这边用的satori是没问题的

**Comment by Pasumao** [comment]
> 我这边用的satori是没问题的
![1](https://github.com/Pasumao/nonebot-plugin-wx4/assets/72342321/fc8429d8-7690-4fc2-a7a3-4377186ac0e4)


我代码写的非常简单，你要是能改自己改一下红框框出来的位置就行，换一个llob支持的获取消息的函数就行

**Comment by danel-phang** [comment]
好的，我试试

**Comment by danel-phang** [comment]
<img width="256" alt="image" src="https://github.com/Pasumao/nonebot-plugin-wx4/assets/145145476/c9ac0dde-c23c-4c60-ab8b-b7a4ab5330c7">
<img width="524" alt="屏幕截图 2024-04-24 155750" src="https://github.com/Pasumao/nonebot-plugin-wx4/assets/145145476/4e613e37-1779-418d-a0e7-6ce56bc3cb47">
OK，可以了
